app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_landingpage.scss
app/assets/stylesheets/components/_login.scss
app/assets/stylesheets/components/_signup.scss
app/controllers/pages_controller.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/pages/landing_page.html.erb

Created landing page. You first see name, description and two buttons (sign in or log in). Each of them leads you to the form you can fill in and create a new account or log in into an existing one. As we don't have the map page by now you will be directed to the first page after the process.

Created landingpage

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb

Fixed landing page. Sign up possible now, added validations

Fixing of landing page

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/models/bar.rb
app/models/subvibe.rb
app/models/user.rb
app/views/users/show.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20240605165635_create_active_storage_tables.active_storage.rb
db/schema.rb
db/seeds.rb

- also made a user show page just to test the cloudinary 
- ran db:seed after all of it and it worked -- but very slow!

Added Cloudinary and Added pics and icons to seeds

---

app/assets/stylesheets/components/_filters_container.scss
app/views/bars/show.html.erb
app/views/layouts/application.html.erb

fixed map page with wrong navbar

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb
db/schema.rb

Magilio font to logo on map page

Edit of Logo font

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_landingpage.scss
app/assets/stylesheets/components/_main_btn.scss
app/assets/stylesheets/components/_tab_btn.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_bar_show.scss
app/assets/stylesheets/pages/_profile_show.scss
app/views/bars/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/landing_page.html.erb
app/views/pages/my_profile.html.erb
app/views/pages/other_profile.html.erb

been testing this all day - just styling plus some bootstrap for the tabs functionality 
checked the map page and that's still all good!
Aureo will merge

Bar and profile tab layout

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_secondary_btn.scss
app/assets/stylesheets/pages/_profile_show.scss
app/controllers/pages_controller.rb
app/controllers/user_subvibes_controller.rb
app/javascript/controllers/tom_select_controller.js
app/views/pages/my_profile.html.erb
config/routes.rb

added delete button to every subvibe list item -- added path to delete user_subvibe
added one create button - added path to create user_subvibe (using a modal instead of a new page)

My subvibes create and delete

---

app/assets/stylesheets/components/_btn_filter.scss
app/javascript/controllers/map_controller.js
app/views/bars/index.html.erb

-button done
-map centers on current location
- blue dot for current location added

current location feature added

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/pages/_bar_show.scss
app/controllers/user_subvibes_controller.rb
app/views/bars/show.html.erb
app/views/pages/my_profile.html.erb
app/views/pages/other_profile.html.erb

set min height to all icon containers (bar and profile pages)
bar image: edited general info text box 
bar image: made them all same width/height
take me there btn = pinned to bottom of screen
edited the flash message when you delete a subvibe (in the usersubvibe controller), and re-styled its posititioning (with the .alert class)

bar page styling done

---

app/assets/stylesheets/components/_landingpage.scss
app/views/pages/landing_page.html.erb

- deleted icons 
- placed 6 icons around header 
- created lightning effects on each icon

Icon placement and lightning

---

app/assets/stylesheets/components/_tab_btn.scss
app/assets/stylesheets/pages/_bar_show.scss
app/javascript/controllers/map_controller.js
app/javascript/controllers/minimap_controller.js
app/views/bars/show.html.erb

-added minimap tab called "Location"
-added minimap
-only one marker with current bar
- CENTERED MAP ON THE TAB

added minimap feature (interactive)

---

app/assets/stylesheets/components/_modal.scss
app/controllers/user_subvibes_controller.rb
app/javascript/controllers/map_button_controller.js
app/models/user_subvibe.rb
app/views/bars/show.html.erb
app/views/pages/my_profile.html.erb
config/locales/devise.en.yml

modal scss: added padding 
user_subvibes_controller: vibe already added notice 
user_subvibe model: validation uniqueness added so you can't add the same subvibe to your profile 
removed sign out and log in notices 
added stimulus to add/remove a d-none class on the mini-map, as the mini-map was messing with the display of the Vibez and Viberz tabs

Create sub v dropdown fix

---

app/javascript/controllers/map_button_controller.js
app/views/bars/show.html.erb

I spotted an error with the initial stimulus in terms of styling. Fixed it with Andre

fixed d-none toggles

---

db/seeds.rb

seeeeeeeeeeeeeeeedsssssssssssssss

too many fucking seeds

---

app/views/bars/show.html.erb

as per ^ title -- Andre and I identified mistake on heroku and fixed together

deleted a 'd' by accident so Vibez tab-btn wasnt working

---

app/views/pages/other_profile.html.erb
db/seeds.rb

-added more seeds
-fixed repeated seeds
-favourites now show up on other_profile view
-fixed typos in seeds
-fixed general stuff
-added random favorites to seeds

general bug fixes and seeding fixes

---

app/assets/stylesheets/components/_login.scss
app/assets/stylesheets/components/_signup.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/pages/my_profile.html.erb
app/views/shared/_navbar.html.erb
config/locales/devise.en.yml

- location in lisbon 
- log out white 
- no back buttons 
- all buttons same font size and color 
- same font size for all headers and all paragraphs

Styling login

---

app/assets/stylesheets/pages/_bar_show.scss

Textdecoration: none

---

app/assets/stylesheets/components/_btn_filter.scss
app/assets/stylesheets/pages/_bar_show.scss

-styled buttons (chaos and open/closed)

quick fixing of some stuff and styling open and closed buttons

---

config/initializers/geocoder.rb
db/seeds.rb

Changed Lisbon addresses to London ones (so I can demonstrate the app more fluently to people in London). 
Refactored the seeding code to make more dry
Also increased Geocoder timeout from 10s to 30s in the config initializer file. This was to remedy an issue where seeded bars were not being displayed on the map.

Reseeded for London, cleaned seed code

---

app/models/user.rb
db/migrate/20240603162808_devise_create_users.rb
db/migrate/20241113161211_add_trackable_to_users.rb
db/migrate/20241113161815_add_more_trackable_to_users.rb
db/schema.rb

Added devise gem's :trackable feature to track usage data. 
Generated corresponding migration files for the user table.

User sign in metric added

---

app/views/pages/landing_page.html.erb

Styling choice. 
Prefer more focus on the Vibez logo in the centre.

Removed Landing Page Icons
